### ISSUE TITLE
Error when running tests

### ISSUE THREAD

**Issue by scmmmh** [pybricks/pybricks-code#1584]
I've been trying to run the tests using Node 18 and am getting the following error:

```
  console.error
    Error: Error: connect ECONNREFUSED 127.0.0.1:80
        at Object.dispatchError (/home/mhall/Projects/pybricks-code/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:63:19)
        at Request.<anonymous> (/home/mhall/Projects/pybricks-code/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
        at Request.emit (node:events:525:35)
        at ClientRequest.<anonymous> (/home/mhall/Projects/pybricks-code/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)
        at ClientRequest.emit (node:events:513:28)
        at Socket.socketErrorListener (node:_http_client:502:9)
        at Socket.emit (node:events:513:28)
        at emitErrorNT (node:internal/streams/destroy:151:8)
        at emitErrorCloseNT (node:internal/streams/destroy:116:3)
        at processTicksAndRejections (node:internal/process/task_queues:82:21) {
      type: 'XMLHttpRequest'
    }

      at VirtualConsole.<anonymous> (node_modules/jest-environment-jsdom/build/index.js:60:23)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:66:53)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
      at ClientRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)

  console.error
    Error: Error: connect ECONNREFUSED 127.0.0.1:80
        at Object.dispatchError (/home/mhall/Projects/pybricks-code/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:63:19)
        at Request.<anonymous> (/home/mhall/Projects/pybricks-code/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
        at Request.emit (node:events:525:35)
        at ClientRequest.<anonymous> (/home/mhall/Projects/pybricks-code/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)
        at ClientRequest.emit (node:events:513:28)
        at Socket.socketErrorListener (node:_http_client:502:9)
        at Socket.emit (node:events:513:28)
        at emitErrorNT (node:internal/streams/destroy:151:8)
        at emitErrorCloseNT (node:internal/streams/destroy:116:3)
        at processTicksAndRejections (node:internal/process/task_queues:82:21) {
      type: 'XMLHttpRequest'
    }

      at VirtualConsole.<anonymous> (node_modules/jest-environment-jsdom/build/index.js:60:23)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:66:53)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
      at ClientRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)

 FAIL  src/mpy/sagas.test.ts
  ✕ compiler works (1039 ms)
  ✕ compiler error works (1010 ms)

  ● compiler works

    TypeError: Network request failed

      at node_modules/whatwg-fetch/dist/fetch.umd.js:535:18
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:519:19)

  ● compiler works

    timed out

      59 |             // completed later
      60 |             return new Promise((resolve, reject) => {
    > 61 |                 const timeout = setTimeout(reject, 1000, new Error('timed out'));
         |                                                          ^
      62 |
      63 |                 this.takers.push({
      64 |                     put: (a: AnyAction): void => {

      at test/index.tsx:61:58
      at AsyncSaga.take (test/index.tsx:60:20)
      at Object.take (src/mpy/sagas.test.ts:13:31)

  ● compiler error works

    TypeError: Network request failed

      at node_modules/whatwg-fetch/dist/fetch.umd.js:535:18
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:519:19)

  ● compiler error works

    timed out

      59 |             // completed later
      60 |             return new Promise((resolve, reject) => {
    > 61 |                 const timeout = setTimeout(reject, 1000, new Error('timed out'));
         |                                                          ^
      62 |
      63 |                 this.takers.push({
      64 |                     put: (a: AnyAction): void => {

      at test/index.tsx:61:58
      at AsyncSaga.take (test/index.tsx:60:20)
      at Object.take (src/mpy/sagas.test.ts:27:31)

```

Am I missing something in my test setup? Any suggestions as to the root cause? Then I can go looking and see if I can fix it.

**Comment by dlech** [comment]
We currently use node 16 so I would suggest sticking with that for now (unless you really want to spend time digging into this problem). We probably need to mock a `fetch()` somewhere so that it isn't trying to make a network connection during tests.

**Comment by scmmmh** [comment]
I'm happy to go digging a bit. Any suggestions as to where I should start?

**Comment by dlech** [comment]
Looking at it closer now, it looks like it has to do with the compiler. This uses the `mpy-cross` executable from MicroPython to compile Python code to a `.mpy` file. The executable is compiled from C to WASM using Emscripten. There is some "magic" in the code generated by Emscripten to handle Node environments vs the web. On Node, it should load the .wasm file from the file system while on the web it uses `fetch()`. It sounds like this may have broke in Node 18?

The source for the `mpy-cross` package is at https://github.com/pybricks/pybricks-micropython/tree/master/npm/mpy-cross.

**Comment by scmmmh** [comment]
That sounds like a likely cause, because it runs just fine and the issue only seemed to appear in the tests. I'll investigate.

Sent from ProtonMail mobile

-------- Original Message --------
